version: '2'

services:
    mongodata:
        image: mongo:3.2
        volumes:
        - /data/db
        entrypoint: /bin/bash
    mongo:
        image: mongo:3.2
        depends_on:
            - mongodata
        volumes_from:
            - mongodata
        ports:
            - "27017"
    zenelectricity:
        image: antoinecheron/zenelectricity
        ports:
            - "8888"
        depends_on:
            - mongo
        links:
            - mongo
    loadbalancer:
            image: dockercloud/haproxy
            depends_on:
                - zenelectricity
            environment:
                - STATS_PORT=1936
                - STATS_AUTH="admin:password"
            links:
                - zenelectricity
            volumes:
                - /var/run/docker.sock:/var/run/docker.sock
            ports:
                - 80:80
                - 1936:1936