export const ADD_POWER_PLANT = 'ADD_POWER_PLANT';

export const REMOVE_POWER_PLANT = 'REMOVE_POWER_PLANT';

export const TURN_PRODUCTION_ON = 'TURN_PRODUCTION_ON';

export const TURN_PRODUCTION_OFF = 'TURN_PRODUCTION_OFF';
